project:
  type: book
  output-dir: docs

book:
  title: "LoggingDiversity"
  date: last-modified
  chapters:
    - index.qmd
    - 01_ideas.qmd
    - 02_plots.qmd
    - 03_ancillary.qmd
    - 04_diversity.qmd
  appendices:
    - 87_ideasold.qmd
    - 96_literature.qmd
    - 97_meeting.qmd
    - 98_contributing.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
