project:
  type: book
  output-dir: docs

book:
  title: "LoggingDiversity"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_data.qmd
      chapters: 
        - 11_plots.qmd
        - 12_logging.qmd
        - 13_ancillary.qmd
    - part: 20_diversity.qmd
      chapters: 
        - 21_species.qmd
  appendices:
    - 87_ideasold.qmd
    - 96_literature.qmd
    - 97_meeting.qmd
    - 98_contributing.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
