project:
  type: book
  output-dir: docs

book:
  title: "LoggingDiversity"
  date: last-modified
  chapters:
    - index.qmd
    - 01_framework.qmd
    - part: 10_data.qmd
      chapters: 
        - 11_inventories.qmd
        - 12_logging.qmd
        - 13_climate.qmd
        - 14_soil.qmd
        - 15_landscape.qmd
        - 16_traits.qmd
        - 17_phylogeny.qmd
    - part: 20_diversity.qmd
      chapters: 
        - 21_species.qmd
        - 22_genus.qmd
    - part: 30_modelling.qmd
      chapters: 
        - 31_short.qmd
        - 32_long.qmd
        - 33_long2.qmd
  appendices:
    - 87_ideasold.qmd
    - 96_literature.qmd
    - 97_meeting.qmd
    - 98_contributing.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
